# Kafka Cluster Smoke test
- name: check Zookeeper is all up
  hosts: <zookeeper-group>
  max_fail_percentage: 0
  roles:
    - check_zk_up

- name: check all kafka brokers are online
  hosts: <kafka-group>[0]
  roles:
    - check_kafka_online


- name: create topic, list topic, produce & consume from topic
  hosts: <kafka-group>[0]
  roles:
    - topic_test_produce_consume